---
# tasks file for node_exporter

- name: Installation curl
  become: true
  ansible.builtin.apt:
    name: curl
    state: present

- name: DL Node node_exporter
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.6.0/node_exporter-1.6.0.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter.tar.gz"
    mode: "0755"

- name: Extraite l'archive
  become: true
  ansible.builtin.unarchive:
    src: "/tmp/node_exporter.tar.gz"
    dest: "/usr/local/bin"
    remote_src: true

- name: Creer user node node_exporter
  become: true
  ansible.builtin.user:
    name: node_exporter
    create_home: false

- name: Déplacer le binaire node_exporter
  become: true
  ansible.builtin.command: mv /usr/local/bin/node_exporter-1.6.0.linux-amd64/node_exporter /usr/local/bin/
  changed_when: true

- name: Supprimer l'archive tar et les fichiers extraits
  become: true
  ansible.builtin.file:
    path: "/tmp/node_exporter.tar.gz"
    state: absent

- name: Créer un service node node_exporter
  become: true
  ansible.builtin.copy:
    content: |
      #!/bin/sh
      ### BEGIN INIT INFO
      # Provides:          node_exporter
      # Required-Start:    $remote_fs $network $syslog
      # Required-Stop:     $remote_fs $network $syslog
      # Should-Start:      $time
      # Should-Stop:       $time
      # Default-Start:     2 3 4 5
      # Default-Stop:      0 1 6
      # Short-Description: Node Exporter
      # Description:       Node Exporter for Prometheus
      ### END INIT INFO

      case "$1" in
        start)
          /usr/local/bin/node_exporter --web.listen-address=:9100 &
          ;;
        stop)
          pkill node_exporter
          ;;
        restart)
          pkill node_exporter
          /usr/local/bin/node_exporter --web.listen-address=:9100 &
          ;;
        *)
          echo "Usage: /etc/init.d/node_exporter {start|stop|restart}"
          exit 1
      esac
      exit 0
    dest: /etc/init.d/node_exporter
    mode: '0755'

- name: Enable and start node_exporter service
  become: true
  ansible.builtin.service:
    name: node_exporter
    enabled: true
    state: started
