---
# tasks file for install_grafana

- name: Installer GPG (gnupg)
  become: true
  ansible.builtin.apt:
    name: gnupg
    state: present

- name: Ajouter la clé GPG du dépôt Grafana
  become: true
  ansible.builtin.apt_key:
    url: "{{ install_grafana_repo_key_url }}"
    state: present

- name: Ajouter le dépôt Grafana
  become: true
  ansible.builtin.apt_repository:
    repo: "deb {{ install_grafana_repo_url }} stable main"
    state: present

- name: Mettre à jour la liste des paquets
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Installer Grafana
  become: true
  ansible.builtin.apt:
    name: grafana={{ install_grafana_version }}
    state: present

- name: Create Prometheus systemd service
  become: true
  ansible.builtin.copy:
    content: |
      #!/bin/bash
      case "$1" in
          start)
              /usr/sbin/grafana-server web &
             ;;
          stop)
              pkill grafana-server
            ;;
          restart)
              pkill grafana-server
              /usr/sbin/grafana-server web &
            ;;
          *)
              echo "Usage: $0 {start|stop|restart}"
              exit 1
      esac
    dest: /etc/init.d/grafana
    mode: '0755'

- name: Assurer que le service Grafana est démarré et activé
  become: true
  ansible.builtin.service:
    name: grafana-server
    enabled: true
    state: started

- name: Modifier le mot de passe administrateur de Grafana
  become: true
  ansible.builtin.lineinfile:
    path: /etc/grafana/grafana.ini
    regexp: '^#admin_password ='
    line: "admin_password = {{ install_grafana_admin_password }}"
  notify: Restart grafana
